<a href="https://colab.research.google.com/github/DeepuKun/Machine-Learning-Practice/blob/main/Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Random Forest is a collection of multipl decision trees

Predict laptop buying occurence using Random forest Algorithm

In [2]:
#libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error, confusion_matrix, classification_report, accuracy_score

In [5]:
#load and upload dataset
data = pd.read_csv('/content/laptop_buying_data.csv', na_values=['',' ','NA','null','NULL','none','?'])

In [7]:
data.head()

    Age  Income Student  Credit Score  Location Buys Laptop
0  25.0    High      No         700.0     Urban         Yes
1  30.0    High     Yes         650.0     Urban          No
2  22.0     Low      No         580.0     Rural          No
3  35.0  Medium      No         620.0     Urban         Yes
4  28.0     Low     Yes         690.0  Suburban         Yes

In [8]:
data.isnull().sum()

Age             1
Income          2
Student         1
Credit Score    2
Location        1
Buys Laptop     0
dtype: int64

In [13]:
#data inspection
#rows
data.shape

(52, 6)

In [16]:
#coloums
print(data.columns.tolist())

['Age', 'Income', 'Student', 'Credit Score', 'Location', 'Buys Laptop']

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           51 non-null     float64
 1   Income        50 non-null     object
 2   Student       51 non-null     object
 3   Credit Score  50 non-null     float64
 4   Location      51 non-null     object
 5   Buys Laptop   52 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.6+ KB

In [20]:
data.describe()

             Age  Credit Score
count  51.000000      50.00000
mean   30.901961     675.20000
std     6.714923      65.90779
min    20.000000     560.00000
25%    26.000000     621.25000
50%    30.000000     667.50000
75%    35.000000     720.00000
max    46.000000     810.00000