<a href="https://colab.research.google.com/github/DeepuKun/Machine-Learning-Practice/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [7]:
data = pd.read_csv('/laptop_buying_data.csv')

In [10]:
data.describe()

             Age
count  51.000000
mean   30.901961
std     6.714923
min    20.000000
25%    26.000000
50%    30.000000
75%    35.000000
max    46.000000

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           51 non-null     float64
 1   Income        50 non-null     object
 2   Student       51 non-null     object
 3   Credit Score  51 non-null     object
 4   Location      51 non-null     object
 5   Buys Laptop   52 non-null     object
dtypes: float64(1), object(5)
memory usage: 2.6+ KB

In [12]:
data.isnull().sum()

Age             1
Income          2
Student         1
Credit Score    1
Location        1
Buys Laptop     0
dtype: int64

In [14]:
data = data.dropna()

In [17]:
data.isnull().sum()

Age             0
Income          0
Student         0
Credit Score    0
Location        0
Buys Laptop     0
dtype: int64

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46 entries, 0 to 51
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           46 non-null     float64
 1   Income        46 non-null     object
 2   Student       46 non-null     object
 3   Credit Score  46 non-null     object
 4   Location      46 non-null     object
 5   Buys Laptop   46 non-null     object
dtypes: float64(1), object(5)
memory usage: 2.5+ KB